#sh

cd ~

#main cli tools
npm install yeoman 
npm install gulp 
npm install grunt 
npm install webpack 
npm install browserify
npm install v8-profiler 
npm install node-inspector 
npm install forever
npm install nodemon 
npm install sass 
npm install casperjs 
npm install jasmine 
npm install jasmine-core
npm install karma 
npm install karma-cli 
npm install jshint 
npm install jslint
npm install jade 
npm install jsdoc 
npm install express
npm install express-generator
npm install dustjs-linkedin
npm install broccoli
npm install bower
npm install bootstrap
npm install babel 
npm install generator-gulp
npm install brunch 
npm install harp 

#other
npm install stacktrace-js 
npm install lodash
npm install jquery 
npm install seneca 
npm install qunit 
npm install yargs 
npm install node-sass 
npm install winston
npm install async
npm install bluebird
npm install flatiron
npm install colors 
npm install chalk
npm install bullet-pubsub
npm install bootstrap-sass
npm install babel-core 
npm install babel-loader 
npm install babel-runtime
npm install karma-jasmine
npm install commander
npm install socket.io
npm install redis
npm install passport
npm install cheerio
npm install merge2
npm install istanbul
npm install backbone

#gulp plugins
npm install gulp-if-else 
npm install gulp-jasmine-browser 
npm install gulp-jasmine-livereload-task
npm install gulp-newer 
npm install gulp-mocha 
npm install gulp-nodemon 
npm install gulp-package 
npm install gulp-param
npm install gulp-plumber 
npm install gulp-dev 
npm install gulp-display-help
npm install gulp-babel
npm install gulp-casperjs
npm install gulp-autoprefixer
npm install gulp-dust 
npm install gulp-es6-transpiler 
npm install gulp-clean 
npm install gulp-exit 
npm install gulp-concat 
npm install gulp-express 
npm install gulp-header 
npm install gulp-imagemin 
npm install gulp-jsdoc 
npm install gulp-jshint 
npm install gulp-regex-replace 
npm install gulp-sass 
npm install gulp-rimrag 
npm install lazypipe 
npm install run-sequence 
npm install gulp-util 
npm install gulp-uglify 
npm install gulp-sweetjs 
npm install gulp-tap 
npm install gulp-template 
npm install gulp-stats 
npm install gulp-shell 
npm install gulp-strip-comments 
npm install gulp-strip-debug 
npm install gulp-word-count 
npm install gulp-wait 
npm install gulp-sourcemaps 
npm install gulp-replace 
npm install gulp-rename 
npm install gulp-livereload 
npm install gulp-print 
npm install gulp-wrap-umd 
npm install gulp-inject 
npm install gulp-cssmin 
npm install gulp-mocha 
